name: SwiftAPNS

options:
  createIntermediateGroups: true
  groupSortPosition: top

attributes:
  ORGANIZATIONNAME: Steven Roebert

packages:
  ConsoleKit:
    url: https://github.com/vapor/console-kit.git
    from: 4.2.4

targets:
  SwiftAPNS:
    type: tool
    platform: macOS
    scheme:
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    sources:
      - path: Sources
    dependencies:
      - package: ConsoleKit
    prebuildScripts:
      - name: Swiftlint
        script: |
          mint run swiftlint lint --config .swiftlint.yml --path Sources
